# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 138941cf47f6618a36928a652198c667ed0d9abb05664089fd73b86a4257e0c5fd0913c92604c84dfd5acf0da5cce07faeb6cecff1ea2eb70747f76d025012b8

test:
  secret_key_base: cac8441b516fe7911c85a3ecf21d2939a055f93adb488a0f34f7c7a7a327668fd76443ced4d6399fd4522feb42d5862041b58f6f0957fcd25f660f770381fc88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
